name: Trigger auto deployment for container-app-zjlvkvtupjbzq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-zjlvkvtupjbzq-AutoDeployTrigger-2f6a3819-ac76-446b-a0b3-9cf83a6f81b9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZJLVKVTUPJBZQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZJLVKVTUPJBZQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZJLVKVTUPJBZQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryzjlvkvtupjbzq.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPZJLVKVTUPJBZQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZJLVKVTUPJBZQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-zjlvkvtupjbzq
          resourceGroup: choreo9225
          imageToBuild: containerregistryzjlvkvtupjbzq.azurecr.io/container-app-zjlvkvtupjbzq:${{ github.sha }}
          dockerfilePath: Dockerfile


